# Generated by Django 6.0 on 2026-05-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
