# Generated by Django 6.0 on 2026-05-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0002_profile_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profiles/'),
        ),
    ]
