# Generated by Django 6.0 on 2026-06-18 21:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0005_transection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='transection',
            new_name='Transaction',
        ),
    ]
