# Generated by Django 6.0 on 2026-06-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0006_rename_transection_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
