# Generated by Django 6.0 on 2026-08-02 10:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0007_alter_transaction_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='reciever',
            new_name='receiver',
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
